# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBPart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Cosmos', '~> 13.0'
	pod 'Firebase/Storage'
	pod 'SVProgressHUD'
	pod 'PINRemoteImage'
  # Pods for HBPart

end
